apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
  namespace: k8s-svc-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In 
                values:
                  - spot-pool
      containers:
      - name: subscriber
        image: northamerica-northeast1-docker.pkg.dev/ruhan-gke-sandbox/gke-pubsub-demo-repo/gke-pubsub-demo:latest
      serviceAccountName: k8s-svc-test